AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Lanchonete Auth (CPF)
Resources:
  AuthFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: src.autenticacao.handler
      Runtime: python3.11
      MemorySize: 256
      Timeout: 10
      Environment:
        Variables:
          USER_POOL_ID: !Ref CognitoUserPool
          JWT_SECRET_NAME: jwtSecret
          LOG_LEVEL: INFO
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - cognito-idp:ListUsers
                - cognito-idp:AdminGetUser
              Resource: "*"
        - Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: !Ref JwtSecret
      Events:
        Api:
          Type: Api
          Properties:
            Path: /auth
            Method: post

  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: LanchoneteAuthPool

  JwtSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: jwtSecret
      SecretString: your-super-secret-key

Outputs:
  ApiUrl:
    Description: "Endpoint da API de autenticação"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/auth"

  UserPoolId:
    Description: "ID do User Pool do Cognito"
    Value: !Ref CognitoUserPool