name: Build
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build SAM Application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: SAM Build
        run: sam build --use-container