

name: Build and Deploy SAM Application

on:
  push:
    branches:
      - main
      - deploy-auth
  pull_request:

jobs:
  build:
    name: Build SAM Application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: SAM Build
        run: sam build --use-container

  deploy:
    name: Deploy SAM Application
    runs-on: ubuntu-latest
    needs: build

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy SAM Application
        run: |
          sam deploy \
            --stack-name "$SAM_STACK_NAME" \
            --region "$AWS_REGION" \
            --config-file samconfig.toml \
            --no-confirm-changeset \
            --no-fail-on-empty-changeset
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SAM_STACK_NAME: ${{ secrets.SAM_STACK_NAME }}