name: Deploy Lambda Auth

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
env:
  AWS_ACCOUNT_ID: ${{ vars.AWS_ACCOUNT_ID }}
  AWS_REGION: ${{ vars.AWS_REGION }}
  AWS_ROLE_TO_ASSUME: ${{ vars.AWS_ROLE_TO_ASSUME }}
  SAM_STACK_NAME: ${{ vars.SAM_STACK_NAME }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_ROLE_TO_ASSUME }}
          role-session-name: gha-lanchonete-auth
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install AWS SAM CLI
        uses: aws-actions/setup-sam@v2
        with:
          version: 1.98.0  # ou mais recente se quiser atualizar

      - name: SAM build
        run: sam build

      - name: SAM deploy
        run: sam deploy --stack-name $SAM_STACK_NAME --config-file samconfig.toml --no-confirm-changeset --no-fail-on-empty-changeset
